### ISSUE TITLE
Annotate online videos other than youtube videos

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/mediaplayer#6]
I saw new [plug in in remnote](https://forum.remnote.io/t/remnote-html-player/9604) which can annotate online videos. Is it  feasible for mediapalyer plug in. I have a huge collection of medical videos and it would be nice to annotate them

**Comment by buggyj** [comment]
it would need a new template!

**Comment by buggyj** [comment]
I have made a template for mp4, I will update the demo in the next day or 2.

**Comment by arunnbabu81** [comment]
> I have made a template for mp4, I will update the demo in the next day or 2.

Is the demo updated?

**Comment by buggyj** [comment]
Not yet - I now have too many templates - I am reorganizing and will put the templates separately. - probably another day or 2.

**Comment by arunnbabu81** [comment]
Any updates @buggyj

**Comment by buggyj** [comment]
I still have to decide how to organize the templates.... I do not want to have to make breaking changes to the templates in the future , if possible

**Comment by arunnbabu81** [comment]
> I still have to decide how to organize the templates.... I do not want to have to make breaking changes to the templates in the future , if possible

I had seen a few days back that new commits were made to the mediaplayer repo. Is it ready for a demo

**Comment by buggyj** [comment]
Hi @arunnbabu81, 
with the annotations I felt that the project was becoming disorganized so I decided to split into a number of plugins - a basic mediaplayer then youtube annotations and video mpeg annotations. I have made some improvements to the templates to allow easy customization.

I have made the templates for the video annotations but the result are disappointing due to issues with the video player widget. I am currently improving the video play and hope to make a release soon. 

You can see a demo of the video annotations at https://mediaplayerava.tiddlyhost.com/
you will seen the problem with 'jumping' when the annotation changes.

**Comment by buggyj** [comment]
@arunnbabu81 I have updated the demo at  https://mediaplayerava.tiddlyhost.com/

**Comment by arunnbabu81** [comment]
> @arunnbabu81 I have updated the demo at https://mediaplayerava.tiddlyhost.com/

I experimented with it today. it works well with local mp4 videos. Is there any new tiddlyclip rules available for clipping local mp4 videos for annotating. I clipped local mp4 videos using the `localmp4 `rule. But I had change the `canonical uri` field to `location` and add the template for it to work.

I guess the mediaplayer and youtube annotation templates have also changed. Let me know when those updates are available for download.

Great work @buggyj
